# Generated by Django 3.1 on 2020-12-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_answer_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='logo',
            field=models.ImageField(default='', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
