# Generated by Django 3.1 on 2020-12-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201204_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bank_name',
            field=models.CharField(choices=[('560', 'Page MFBank'), ('304', 'Stanbic Mobile Money'), ('308', 'FortisMobile'), ('328', 'TagPay'), ('309', 'FBNMobile'), ('011', 'First Bank of Nigeria'), ('326', 'Sterling Mobile'), ('990', 'Omoluabi Mortgage Bank'), ('311', 'ReadyCash (Parkway)'), ('057', 'Zenith Bank'), ('068', 'Standard Chartered Bank'), ('306', 'eTranzact'), ('070', 'Fidelity Bank'), ('023', 'CitiBank'), ('215', 'Unity Bank'), ('323', 'Access Money'), ('302', 'Eartholeum'), ('324', 'Hedonmark'), ('325', 'MoneyBox'), ('301', 'JAIZ Bank'), ('050', 'Ecobank Plc'), ('307', 'EcoMobile'), ('318', 'Fidelity Mobile'), ('319', 'TeasyMobile'), ('999', 'NIP Virtual Bank'), ('320', 'VTNetworks'), ('221', 'Stanbic IBTC Bank'), ('501', 'Fortis Microfinance Bank'), ('329', 'PayAttitude Online'), ('322', 'ZenithMobile'), ('303', 'ChamsMobile'), ('403', 'SafeTrust Mortgage Bank'), ('551', 'Covenant Microfinance Bank'), ('415', 'Imperial Homes Mortgage Bank'), ('552', 'NPF MicroFinance Bank'), ('526', 'Parralex'), ('035', 'WemaBank'), ('084', 'Enterprise Bank'), ('063', 'Diamond Bank'), ('305', 'Paycom'), ('100', 'SunTrust Bank'), ('317', 'Cellulant'), ('401', 'ASO Savings and & Loans'), ('030', 'Heritage'), ('402', 'Jubilee Life Mortgage Bank'), ('058', 'GTBank Plc'), ('032', 'Union Bank'), ('232', 'Sterling Bank'), ('076', 'Skye Bank'), ('082', 'Keystone Bank'), ('327', 'Pagatech'), ('559', 'Coronation Merchant Bank'), ('601', 'FSDH'), ('313', 'Mkudi'), ('214', 'First City Monument Bank'), ('314', 'FET'), ('523', 'Trustbond'), ('315', 'GTMobile'), ('033', 'United Bank for Africa'), ('044', 'Access Bank')], default='', max_length=6),
        ),
    ]
