# Generated by Django 3.1 on 2020-12-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_survey_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
