# Generated by Django 3.1 on 2020-12-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_patient_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='account_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
