# Generated by Django 3.1 on 2020-12-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201208_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='logo',
        ),
    ]
